const actionTypes = {
    SET_CUSTOMERS: 'SET_CUSTOMERS',
    SELECTED_CUSTOMER: 'SELECTED_CUSTOMER',
    REMOVE_SELECTED_CUSTOMER: 'REMOVE_SELECTED_CUSTOMER',
    SET_PAYMENTS: 'SET_PAYMENTS'
}

export default actionTypes;